/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  theme: {
    extend: {
      colors: {
        "ion-background-color": "var(--ion-background-color)",
        "ion-background-color-rgb": "var(--ion-background-color-rgb)",

        "ion-text-color": "var(--ion-text-color)",
        "ion-text-color-rgb": "var(--ion-text-color-rgb)",

        "ion-text-color-step-50": "var(--ion-text-color-step-50)",
        "ion-text-color-step-100": "var(--ion-text-color-step-100)",
        "ion-text-color-step-150": "var(--ion-text-color-step-150)",
        "ion-text-color-step-200": "var(--ion-text-color-step-200)",
        "ion-text-color-step-250": "var(--ion-text-color-step-250)",
        "ion-text-color-step-300": "var(--ion-text-color-step-300)",
        "ion-text-color-step-350": "var(--ion-text-color-step-350)",
        "ion-text-color-step-400": "var(--ion-text-color-step-400)",
        "ion-text-color-step-450": "var(--ion-text-color-step-450)",
        "ion-text-color-step-500": "var(--ion-text-color-step-500)",
        "ion-text-color-step-550": "var(--ion-text-color-step-550)",
        "ion-text-color-step-600": "var(--ion-text-color-step-600)",
        "ion-text-color-step-650": "var(--ion-text-color-step-650)",
        "ion-text-color-step-700": "var(--ion-text-color-step-700)",
        "ion-text-color-step-750": "var(--ion-text-color-step-750)",
        "ion-text-color-step-800": "var(--ion-text-color-step-800)",
        "ion-text-color-step-850": "var(--ion-text-color-step-850)",
        "ion-text-color-step-900": "var(--ion-text-color-step-900)",
        "ion-text-color-step-950": "var(--ion-text-color-step-950)",

        "ion-background-color-step-50": "var(--ion-background-color-step-50)",
        "ion-background-color-step-100": "var(--ion-background-color-step-100)",
        "ion-background-color-step-150": "var(--ion-background-color-step-150)",
        "ion-background-color-step-200": "var(--ion-background-color-step-200)",
        "ion-background-color-step-250": "var(--ion-background-color-step-250)",
        "ion-background-color-step-300": "var(--ion-background-color-step-300)",
        "ion-background-color-step-350": "var(--ion-background-color-step-350)",
        "ion-background-color-step-400": "var(--ion-background-color-step-400)",
        "ion-background-color-step-450": "var(--ion-background-color-step-450)",
        "ion-background-color-step-500": "var(--ion-background-color-step-500)",
        "ion-background-color-step-550": "var(--ion-background-color-step-550)",
        "ion-background-color-step-600": "var(--ion-background-color-step-600)",
        "ion-background-color-step-650": "var(--ion-background-color-step-650)",
        "ion-background-color-step-700": "var(--ion-background-color-step-700)",
        "ion-background-color-step-750": "var(--ion-background-color-step-750)",
        "ion-background-color-step-800": "var(--ion-background-color-step-800)",
        "ion-background-color-step-850": "var(--ion-background-color-step-850)",
        "ion-background-color-step-900": "var(--ion-background-color-step-900)",
        "ion-background-color-step-950": "var(--ion-background-color-step-950)",
      },
    },
  },
  plugins: [],
};
